# Generated by Django 3.1.6 on 2021-02-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش نویس'), ('pending', 'در انتظار'), ('publish', 'انتشار')], default='publish', max_length=20),
        ),
    ]
