# Generated by Django 3.1.6 on 2021-02-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210216_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='en_title',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200, null=True, unique=True),
        ),
    ]
