version: '3.9'

services:
  web:
    container_name: baboon_django_dev
    build: ./django
    restart: always
    volumes:
      - ./django/:/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    container_name: baboon_postgres_dev
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=django_app

volumes:
  db_data: