# Generated by Django 3.1.4 on 2020-12-16 12:44

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image', sorl.thumbnail.fields.ImageField(max_length=255, upload_to='images/%Y/%m/%d')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
