# Generated by Django 3.1.4 on 2020-12-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
